SELECT COUNT(*) FROM TABELA_DE_CLIENTES;
SELECT COUNT(*) FROM TABELA_DE_PRODUTOS;
SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <= 18

SELECT COUNT(TABELA_DE_CLIENTES.NOME) FROM TABELA_DE_CLIENTES WHERE TABELA_DE_CLIENTES.NOME LIKE '%Silva%'

SELECT DISTINCT
	COUNT(SABOR) AS SABORES
FROM TABELA_DE_PRODUTOS

SELECT TOP 10 * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '2017-10-01';
